# Generated by Django 3.0.2 on 2020-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='orders.Service'),
        ),
    ]
