# Generated by Django 3.0.2 on 2020-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200125_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='car',
            field=models.CharField(blank=True, max_length=250, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='account',
            name='testimonial',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
    ]
