# Generated by Django 3.0.2 on 2020-02-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200202_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
